BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mcp2515-pi5"
BBFILE_PATTERN_mcp2515-pi5 = "^${LAYERDIR}/"
BBFILE_PRIORITY_mcp2515-pi5 = "7"

LAYERDEPEND_mcp2515-pi5 = "core"
LAYERSERIES_COMPAT_mcp2515-pi5 = "scarthgap"
