# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/ipc/yocto-rpi/poky/meta \
  /home/ipc/yocto-rpi/poky/meta-poky \
  /home/ipc/yocto-rpi/poky/meta-yocto-bsp \
  /home/ipc/yocto-rpi/poky/meta-raspberrypi \
  /home/ipc/yocto-rpi/poky/meta-openembedded/meta-oe \
  /home/ipc/yocto-rpi/poky/meta-openembedded/meta-python \
  /home/ipc/yocto-rpi/poky/meta-openembedded/meta-networking \
  /home/ipc/yocto-rpi/poky/meta-openembedded/meta-multimedia \
  /home/ipc/yocto-rpi/poky/meta-qt5 \
  /home/ipc/yocto-rpi/poky/meta-mywifi \
  /home/ipc/yocto-rpi/poky/meta-dashboard \
  /home/ipc/yocto-rpi/poky/meta-linkupcan \
  /home/ipc/yocto-rpi/poky/meta-mcp2515-pi5 \
  "
