ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=0
update_config=0
country=VN

network={
    ssid="THANH PHUC"
    psk="Thanhphuc3108@"
    key_mgmt=WPA-PSK
    priority=2
}

network={
    ssid="Binh An"
    psk="LeAn1910"
    key_mgmt=WPA-PSK
    priority=2
}

network={
    ssid="VCU_Wifi"
    psk="123456789"
    key_mgmt=WPA-PSK
    priority=1
}
