BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-linkupcan"
BBFILE_PATTERN_meta-linkupcan = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-linkupcan = "8"

LAYERDEPENDS_meta-linkupcan = "core"
LAYERSERIES_COMPAT_meta-linkupcan = "scarthgap"
